#Formatting String video 94
#format () method part1

print("this is format method in python vid94\n")
print("----------integer-----------")
print("{}".format(10))
print("{} {}".format(10,20))
print("0".format(10))
print("{0} {1}".format(10,20))
print("{1} {0}".format(10,20))
print("{num1}".format(num1=10))
print("{num1} {num2}".format(num1=10,num2=20))
print("{num2} {num1}".format(num1=10,num2=20))
print("------------Integer and string-----------\n")
print("Hello My Name Is {}".format("Krish"))
print("{} {}".format(10,"pandit"))
print("{0} {1}".format(10,"pandit"))
print("{1} {0}".format(10,"pandit"))
print("{num1} {str1}".format(num1=10,str1="panditprogrammer"))
print("{str1} {num1}".format(num1=10,str1="panditprogrammer"))