#Formatting String video 94
#format () method part2
"""this is 
multiline comments in python """
print("fomating string and method rules")
print("----------integer---------")
print("{}".format(15))
print("{:d}".format(15))
print("{0:d}".format(15))
print("{num:d}".format(num=15))
print("----------float---------\n")
print("{}".format(15.65))
print("{:f}".format(15.65))
print("{0:f}".format(15.65))
print("{num:f}".format(num=15.65))
print("----------float and more---------\n")
print("{num:f}".format(num=10.2))
print("{num:8f}".format(num=10.2))
print("{num:8.3f}".format(num=10.2))
print("{num:+8.2f}".format(num=10.2))
print("{num:<8.2f}".format(num=10.2))
print("{num:*<8.2f}".format(num=10.2))
print("{num:*>8.2f}".format(num=10.2))
print("{num:^8.2f}".format(num=10.2))
print("{num:*^8.2f}".format(num=10.2))
# # print("----------string and its rules---------\n")
# # print("{str1:s}".format(str1="Panditprogrammer"))
# print("{str1:20s}".format(str1="Panditprogrammer")) 
# print("{str1:20.s}".format(str1="Panditprogrammer"))
# print("{str1:<20.s}".format(str1="Panditprogrammer"))
# print("{str1:>20.s}".format(str1="Panditprogrammer"))
# print("{str1:*<20.s}".format(str1="Panditprogrammer"))
# print("{str1:*>20.s}".format(str1="Panditprogrammer"))
# print("{str1:^20.s}".format(str1="Panditprogrammer"))
# print("{str1:*^20.s}".format(str1="Panditprogrammer"))