#output statements in python
print('this is print functions for  output statements. ')
print('like ' ,'share' ,'subucribe')
print()
print('me', 'my computer')
print(10)
print(type(20))
print('welcome')
print('to')
print('myshows.com')
print("like","share","subucribe" ,sep='  ')
print("welcome", end='\t ')
print('to', end='\t')
m=30
print("Rahl" ,m)